services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development
    networks:
      - test-net
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - test-net
    ports:
      - 3000:3000
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    networks:
      - test-net
    ports:
      - 27017:27017
networks:
  test-net:
